name: Working Dirs & Shells
on: [push]
defaults:
  run:
    shell: bash
  # working-directory: /your_directory/nested_directory
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working Directory & List files
        run: |
          pwd
          ls -al
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change default Working Dir
        working-directory: /home/runner
        run: |
          pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display working Directory & List files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: Python Shell
        shell: python
        run: |
          import platform
          print(platform.processor())